http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:5590
  session_ttl: 720h
users:
  - name: admin
    password: $2a$10$JaPRtIqOpm1l6.Id9alHXOT/Q9dcKJ3Dvtko8NhZbnsC1MpPcW./O
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - https://dns10.quad9.net/dns-query
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
    - https://dns.alidns.com/dns-query
    - https://dns10.quad9.net/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
    - 101.226.4.6
    - 180.76.76.76
    - 117.50.10.10
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
  fallback_dns: []
  all_servers: true
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients:
    - 36.128.0.0/10
    - 39.128.0.0/10
    - 43.239.172.0/22
    - 43.251.244.0/22
    - 45.121.68.0/22
    - 45.121.72.0/22
    - 45.121.172.0/22
    - 45.121.176.0/22
    - 45.122.96.0/21
    - 45.123.152.0/22
    - 45.124.36.0/22
    - 45.125.24.0/22
    - 45.253.72.0/22
    - 61.14.240.0/22
    - 61.14.244.0/22
    - 103.20.112.0/22
    - 103.21.176.0/22
    - 103.35.104.0/22
    - 103.61.156.0/22
    - 103.61.160.0/22
    - 103.62.24.0/22
    - 103.62.204.0/22
    - 103.62.208.0/22
    - 103.192.0.0/22
    - 103.192.144.0/22
    - 103.193.140.0/22
    - 103.203.164.0/22
    - 103.205.108.0/22
    - 103.205.116.0/22
    - 103.222.196.0/22
    - 111.0.0.0/10
    - 112.0.0.0/10
    - 117.128.0.0/10
    - 120.192.0.0/10
    - 175.176.188.0/22
    - 183.192.0.0/10
    - 211.103.0.0/17
    - 211.136.0.0/14
    - 211.140.0.0/15
    - 211.142.0.0/17
    - 211.142.128.0/17
    - 211.143.0.0/16
    - 218.200.0.0/14
    - 218.204.0.0/15
    - 218.206.0.0/15
    - 221.130.0.0/15
    - 221.176.0.0/13
    - 223.64.0.0/11
    - 223.96.0.0/12
    - 223.112.0.0/14
    - 223.116.0.0/15
    - 223.120.128.0/17
    - 223.121.128.0/17
    - 223.122.128.0/17
    - 223.123.128.0/17
    - 223.124.0.0/14
    - 49.64.0.0/11
    - 180.96.0.0/11
    - 58.208.0.0/12
    - 114.224.0.0/12
    - 117.80.0.0/12
    - 121.224.0.0/12
    - 114.216.0.0/13
    - 221.224.0.0/13
    - 222.184.0.0/13
    - 117.60.0.0/14
    - 222.92.0.0/14
    - 218.2.0.0/15
    - 218.4.0.0/15
    - 61.132.0.0/16
    - 61.160.0.0/16
    - 61.177.0.0/16
    - 202.111.0.0/17
    - 202.102.64.0/18
    - 202.102.0.0/19
    - 202.102.32.0/19
    - 103.12.68.0/23
    - 103.22.20.0/22
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 600
  cache_ttl_max: 3600
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  ignored: []
  interval: 168h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  ignored: []
  interval: 168h
  enabled: true
filters:
  - enabled: false
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
    name: anti-AD
    id: 1652091008
  - enabled: true
    url: https://raw.githubusercontent.com/lhbill/xiaomiad/master/xiaomi.txt
    name: 小米盒子广告
    id: 1652091011
  - enabled: true
    url: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
    name: 大圣净化 - 针对国内视频网站
    id: 1652091012
  - enabled: true
    url: https://gist.githubusercontent.com/Ewpratten/a25ae63a7200c02c850fede2f32453cf/raw/b9318009399b99e822515d388b8458557d828c37/hosts-yt-ads
    name: youtube-去广告
    id: 1661490770
  - enabled: true
    url: https://www.i-dont-care-about-cookies.eu/abp
    name: I don't care about cookies
    id: 1661490772
  - enabled: true
    url: https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
    name: Adgk手机去广告规则
    id: 1661490773
  - enabled: true
    url: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts
    name: 1024网站及澳门皇家赌场
    id: 1661490774
  - enabled: true
    url: https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt
    name: Cats-team/Adrule
    id: 1661490775
  - enabled: true
    url: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
    name: CJX'sAnnoyance
    id: 1661490776
  - enabled: true
    url: https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt
    name: 百度搜索结果内屏蔽百家号
    id: 1697279163
whitelist_filters: []
user_rules:
  - '@@||api.io.mi.com^'
  - '@@||amdc.m.taobao.com^$important'
  - '@@||amdc.alipay.com^$important'
  - '@@||zz.bdstatic.com^$important'
  - '@@||adashx.m.taobao.com^$important'
  - '||douyin.com^'
  - '||api.assistant.miui.com^'
  - '||d.douyin.com^'
  - '||s5.ssl.qhimg.com^'
  - '||hub5pr.sandai.net^'
  - '||sf0.market.xiaomi.com^'
  - '@@||media.ptmi.gitv.tv^$important'
  - '@@||broker.mqtt.pandora.xiaomi.com^$important'
  - '@@||pandora.mi.com^$important'
  - '@@||ott.io.mi.com^$important'
  - '@@||mitv.tracking.miui.com^$important'
  - '@@||ottimg.cdn.pandora.xiaomi.com^$important'
  - '@@||gstat.ptmi.gitv.tv^$important'
  - '@@||data.mistat.xiaomi.com^$important'
  - '@@||image.box.xiaomi.com^$important'
  - '#酷喵影视广告规则'
  - '||ipm.atm.cp31.ott.cibntv.net^'
  - '||val.atm.cp31.ott.cibntv.net^'
  - '||valf.atm.cp31.ott.cibntv.net^'
  - '||vali.cp31.ott.cibntv.net^'
  - '||vali.cp31.ott.cibntv.net.302.myalicdn.com^'
  - '||abtest.alibaba.com^'
  - '||ems.cp31.ott.cibntv.net^'
  - '||youku-dtv.m.cn.miaozhen.com^'
  - '||pl.cp31.ott.cibntv.net^'
  - '||nbsdk-baichuan.alicdn.com^'
  - '||acs.m.taobao.com^'
  - '||wgo.mmstat.com^'
  - '||proxy-mob-cld.alicdn.com^'
  - '||image.9xsecndns.cn^'
  - '||adashx4yt.m.taobao.com^'
  - '||px.ucweb.com^'
  - '||sjarvis.taobao.com^'
  - '||ipm.atm.youku.com^'
  - '||huichuan.sm.cn^'
  - '||audid-api.taobao.com^'
  - '||applog.uc.cn^'
  - '||orange-dc.youku.com^'
  - '||youku-acs.m.taobao.com^'
  - '||acs4baichuan.m.taobao.com^'
  - '||ykugc.cp31.ott.cibntv.net^'
  - '||vali-dns.cp31.ott.cibntv.net^'
  - '||heyi-acs.cp31.ott.cibntv.net^'
  - '#小米遥控器'
  - '||cnbj1.fds.api.xiaomi.co^'
  - '#YouTube广告'
  - /googleads.$~script,domain=~googleads.github.io
  - /pagead/lvz?
  - '||google.com/pagead/'
  - '||static.doubleclick.net^$domain=youtube.com'
  - '||youtube.com/get_midroll_'
  - '||safebrowsing.googleapis-cn.com'
  - '||doubleclick.net'
  - '#秋风のとおり道 电报频道 https://t.me/AWAvenue'
  - '||wxsnsdy.wxs.qq.com^'
  - 127.0.0.1 wxsnsdy.wxs.qq.com
  - '||wxa.wxs.qq.com^'
  - 127.0.0.1 wxa.wxs.qq.com
  - '||wxsnsdythumb.wxs.qq.com^'
  - 127.0.0.1 wxsnsdythumb.wxs.qq.com
  - '||is.snssdk.com^'
  - '||i.snssdk.com^'
  - '||p3-tt.byteimg.com^'
  - '||success.ctobsnssdk.com^'
  - '||sf16-static.i18n-pglstatp.com^'
  - '||sf3-fe-tos.pglstatp-toutiao.com^'
  - '||ad.zijieapi.com^'
  - '||api-access.pangolin-sdk-toutiao.com^'
  - '||mobads.baidu.com^'
  - '||ad.qq.com^'
  - '||ks.pull.yximgs.com^'
  - '||open.e.kuaishou.com^'
  - '||open.e.kuaishou.cn^'
  - '||open.e.kuaishou^'
  - '||open.kwaizt.com^'
  - '||bd.pull.yximgs.com^'
  - '||jstatic.3.cn^'
  - '||p1-lm.adukwai.com^'
  - '||p2-lm.adukwai.com^'
  - '||p3-lm.adukwai.com^'
  - '||p4-lm.adukwai.com^'
  - '||p5-lm.adukwai.com^'
  - '||m.jingxi.com^'
  - '||chat1.jd.com^'
  - 127.0.0.1 www.csjplatform.com
  - '||www.csjplatform.com^'
  - '||xlmzc.cnjp-exp.com^'
  - '||lm10111.jtrincc.cn^'
  - '||ali-ad.a.yximgs.com^'
  - '||qqdata.ab.qq.com^'
  - '||tx-ad.a.yximgs.com^'
  - '||p1-lm.adkwai.com^'
  - '||video-dsp.pddpic.com^'
  - '||v1-lm.adukwai.com^'
  - '||v2-lm.adukwai.com^'
  - '||v3-lm.adukwai.com^'
  - '||v4-lm.adukwai.com^'
  - '||v5-lm.adukwai.com^'
  - '||pgdt.ugdtimg.com^'
  - '||tx-kmpaudio.pull.yximgs.com^'
  - '||hmma.baidu.com^'
  - '||apiyd.my91app.com^'
  - '||open.kuaishouzt^'
  - '||qzs.gdtimg.com^'
  - '||sdkoptedge.chinanetcenter.com^'
  - '||roi.soulapp.cn^'
  - '||bd.pull.yximgs.com^'
  - '||bd-adaptive.pull.yximgs.com^'
  - '||bd-livemate.pull.yximgs.com^'
  - '||bd-origin.pull.yximgs.com^'
  - '||bd-pclivemate.pull.yximgs.com^'
  - '||bd-proxy.pull.yximgs.com^'
  - '||bd-rwk.pull.etoote.com^'
  - '||httpdns.bcelive.com^'
  - '||skdisplay.jd.com^'
  - '||p9-be-pack-sign.pglstatp-toutiao.com^'
  - '||v6-be-pack.pglstatp-toutiao.com^'
  - '||log-api.pangolin-sdk-toutiao-b.com^'
  - '||api-access.pangolin-sdk-toutiao-b.com^'
  - '||pangolin-sdk-toutiao-b.com^'
  - '||pig.pupuapi.com^'
  - '||pglstatp-toutiao.com^'
  - '||thumb.1010pic.com^'
  - '||thumb2018.1010pic.com^'
  - '||1010pic.com^'
  - ""
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: Local
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 27
