bind_host: 0.0.0.0
bind_port: 80
beta_bind_port: 0
users:
  - name: 7gPWZVygkABog9q8K
    password: $2a$10$nuGZa1vxwD74NNEgKrP.m.37shVxe3B7tgtTZ3.xS1v/2u49Po1bm
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  statistics_interval: 30
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 720h
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - 8.8.8.8
    - https://dns.alidns.com/dns-query
    - https://dns10.quad9.net/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
    - 101.226.4.6
    - 180.76.76.76
    - 117.50.10.10
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 83886079
  cache_ttl_min: 2
  cache_ttl_max: 86400
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
  - enabled: false
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: false
    url: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
    name: anti-AD
    id: 1652091008
  - enabled: true
    url: https://raw.githubusercontent.com/lhbill/xiaomiad/master/xiaomi.txt
    name: 小米盒子广告
    id: 1652091011
  - enabled: true
    url: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
    name: 大圣净化 - 针对国内视频网站
    id: 1652091012
  - enabled: true
    url: https://gist.githubusercontent.com/Ewpratten/a25ae63a7200c02c850fede2f32453cf/raw/b9318009399b99e822515d388b8458557d828c37/hosts-yt-ads
    name: youtube-去广告
    id: 1661490770
  - enabled: true
    url: https://www.i-dont-care-about-cookies.eu/abp
    name: I don't care about cookies
    id: 1661490772
  - enabled: true
    url: https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
    name: Adgk手机去广告规则
    id: 1661490773
  - enabled: true
    url: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts
    name: 1024网站及澳门皇家赌场
    id: 1661490774
  - enabled: true
    url: https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt
    name: Cats-team/Adrule
    id: 1661490775
  - enabled: true
    url: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
    name: CJX'sAnnoyance
    id: 1661490776
whitelist_filters: []
user_rules:
  - '@@||api.io.mi.com^'
  - '||douyin.com^'
  - '||api.assistant.miui.com^$important'
  - '||d.douyin.com^$important'
  - '||s5.ssl.qhimg.com^$important'
  - '||hub5pr.sandai.net^$important'
  - '||sf0.market.xiaomi.com^$important'
  - '@@||media.ptmi.gitv.tv^$important'
  - '@@||broker.mqtt.pandora.xiaomi.com^$important'
  - '@@||pandora.mi.com^$important'
  - '@@||ott.io.mi.com^$important'
  - '@@||mitv.tracking.miui.com^$important'
  - '@@||ottimg.cdn.pandora.xiaomi.com^$important'
  - '@@||gstat.ptmi.gitv.tv^$important'
  - '@@||data.mistat.xiaomi.com^$important'
  - '@@||image.box.xiaomi.com^$important'
  - '@@||adashx.m.taobao.com^$important'
  - '@@||amdc.alipay.com^$important'
  - '@@||amdc.m.taobao.com^$important'
  - ""
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log_file: ""
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_compress: false
log_localtime: false
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 14
